### ISSUE TITLE
OSX 1.3.1 build

### ISSUE THREAD

**Issue by revolunet** [apngasm/apngasm#45] opened 2015-05-20 12:02 UTC
Hey,

I have this issue when running the OSX binary (1.3.1 release):

looks like there is some hardcoded path

```sh
apngasm -v
dyld: Library not loaded: /Users/nazuki/repo/apngasm/build/lib/libapngasm.dylib
  Referenced from: /usr/bin/apngasm
  Reason: image not found
Trace/BPT trap: 5
```

Also tried to `brew install` too but for some reason, apngasm prints "X Frames" but does not produce any file

Thanks for your suggestions

**Comment by Kagetsuki** [comment] 2015-05-21 04:58
Thanks for the heads up.

We'll only be releasing newer versions on homebrew from now on. Please use the brew version. I'll assign this to @R-Y but she won't be able to take a look at it for about a week.

**Comment by Kagetsuki** [comment] 2015-05-27 03:15
@revolunet We just confirmed a homebrew install on a clean OSX and it seems to be working. Please confirm the following:

1. The files you are using are all proper PNG files
2. All frame files are the same size (width x height)

Also please post the output of apngasm -v . Perhaps the older version is still installed?

**Closed by Kagetsuki** 2015-05-27 03:15 UTC
